version: '3'

services:
  jackspizza:
    build: ./jackspizza
    #command: python3 manage.py runserver 0.0.0.0:8888
    command: gunicorn pizza.wsgi
    volumes:
      - ./jackspizza:/usr/src/app
    ports:
      - 8888:8000
